Update README.md to reference latest version
Gioni06/terminal.css pull request #48
Opened 2024-06-19 17:08 UTC by komidore64

2025-03-15 19:59 UTC, RobLoach requested changes
You can even reference it directly and it will grab the latest automagically for you: https://unpkg.com/terminal.css

2025-03-15 19:59 UTC, RobLoach commented on README.md
> +Terminal CSS is also available via [CDN](https://unpkg.com/terminal.css@0.7.5/dist/terminal.min.css)
``` suggestion
Terminal CSS is also available via [CDN](https://unpkg.com/terminal.css)
```

2025-03-15 19:59 UTC, RobLoach commented on README.md
> +<link rel="stylesheet" href="https://unpkg.com/terminal.css@0.7.5/dist/terminal.min.css" />
``` suggestion
<link rel="stylesheet" href="https://unpkg.com/terminal.css" />
```

2025-03-17 14:50 UTC, komidore64 commented
@RobLoach good idea!

2025-08-24 12:21 UTC, merged